### ISSUE TITLE
Melhorias no Perfil do Usuário

### ISSUE THREAD

**Issue by leonardo-silva** [brenovambaster/Projeto-TreeManager#11]
- Alteração de senha deve ser uma opção separada, com confirmação da senha atual e inclusão de nova senha.
OBS: Senha deve ser criptografada no BD.

- A tela possui um rosto cinza, que sugere a inclusão de uma imagem (foto). Mas não tem essa opção. Vai ter possibilidade de upload de foto?

- Ao salvar uma alteração, clicando no botão Editar, aparece uma página em branco com o texto: "success editar" e não volta para o perfil do usuário. Essa msg de "Edição com sucesso" não precisa abrir outra página.

- Acredito que a opção "Limpar" não faz sentido nessa tela. Mesmo porque não funciona.

**Comment by brenovambaster** [comment]
- Com relação a senha, irei modificar e colocar em uma opção separada.
- Até então, eu  não tinha pensado em carregar uma foto para cada usuário. Mas é uma opção válida e podemos incrementá-la. Irá depender somente  de vocês.
- Esse redirecionamento (e outros que ocorrem) é um erro de interpretação do servidor onde o site está hospedado. Por ser um serviço gratuito, apresenta algumas falhas. No entanto, quando rodar o projeto em Localhost o redirecionamento ocorre sem falhas. 
    Pode-se perceber ao clilcar  [AQUI](https://github.com/brenovambaster/Projeto-TreeManager/blob/master/user/EditarPerfil.php)  que na linha 14,19 e 22 existe um comando de redirecionar
```php
header("location:perfil.php?");
```
Mas o servidor  web, por algum motivo, não está redirecionado. Sugiro que faça o teste localmente.
- A opção "Limpar" limpa apenas modificações feitas antes de serem <strong>salvas.</strong> 
Ex: Ao alterar o valor do  campo `nome`(sem  salvar a modificação) e  clicar em `"limpar"` as modificações são desfeitas;  apresentando apenas o conteúdo já existente no DB.

**Comment by leonardo-silva** [comment]
- Acho interessante sim implementar a opção de carregar foto de perfil.

- Acho então que o botão 'Limpar' deveria ser alterado para 'Desfazer', e só ficar habilitado qdo houver algo para desfazer. Trocaria tbm o 'Editar' por 'Salvar', deixando habilitado apenas qdo houver algo para salvar.

**Comment by brenovambaster** [comment]
https://github.com/brenovambaster/Projeto-TreeManager/issues/11#issuecomment-629349126
Problemas resolvidos pelo commit: 
> remover/inserir foto de perfil [ver commit](https://github.com/brenovambaster/Projeto-TreeManager/commit/009fec36f689750e6db1ee3ac402a0f6ca788e29)

- [x] renomear botões;
- [x] Carregar Foto;
- [x] Opção separada, com confirmação da senha atual e inclusão de nova senha;
- [x] Habilitar/ Desabilitar botões;

**Comment by brenovambaster** [comment]
- ### Os problemas supracitados foram resolvidos.
 > Ver branch [versao3.2](https://github.com/brenovambaster/Projeto-TreeManager/tree/versao3.2)
