### ISSUE TITLE
Gerenciamento de árvores

### ISSUE THREAD

**Issue by leonardo-silva** [brenovambaster/Projeto-TreeManager#12]
- O link 'Ver', para a árvore de exemplo ID=18, exibe a seguinte msg: "A operação nao pode ser realizada pois a árvore já foi validada pelo adm. Para que possa editar as informações, solicite uma serviço de edição para a árvore de ID=18". Não faz sentido se eu quero apenas ver.

- Ao cadastrar um serviço de reparo de danos: "id arvore 18 2020,05,23aee deu certo". É necessário definir um padrão para mensagens de confirmação e também de erro. 

- Ao pesquisar por uma árvore, aquela que atende ao critério de busca fica e as demais somem. Isso está ok, mas deveria ter uma maneira de voltar/limpar a pesquisa, mostrando novamente todas as árvores.

**Comment by brenovambaster** [comment]
- De fato, é um erro e não faz sentido.  Mas isso ocorre porque eu não redirecionei para a página correta. No caso, eu deveria ter redirecionado para a página de `leitura_arvore.php`(e não para o `formulario.php`) para que se possa ver os dados daquela árvore. Vou fazer o redirecionamento correto.
- Concordo que se deve padronizar as mensagens de erro ou confirmação. No entanto, como disse em outras vezes, o servidor não está interpretando o comando
```php
 header("Location:solicitacoes.php");
``` 
 Apareceu a mensagem de confirmação mas não foi redirecionado. Em uma interpretação correta, era pra ter ocorrido o redirecionamento pois o comando na linha 29 está correto. [[ver código]](https://github.com/brenovambaster/Projeto-TreeManager/blob/master/user/valida_servico.php) 
- Se eu  tiver entendido bem, isso já é possível. Basta clicar em `pesquisar` sem inserir nenhum dado nos campos. Dessa forma, irá mostrar todas as árvores.  Mas se quiser inserir algum dado, não tem problema. Pois será feita a pesquisa com base nos campos preenchidos. Se apenas 1 campo for preenchido, a pesquisa será apenas por ele. Se pesquisar com nenhum campo preenchido, a pesquisa será por todas as árvores.
- _obs*Farei essas alterações. qualquer dúvida ou erro, comunique._

**Comment by brenovambaster** [comment]
Resolvido pelo commit:
> resolvendo issue 12
